# Generated by Django 5.1.7 on 2025-11-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_attendance_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='snapshots/processed/%Y/%m/%d/'),
        ),
    ]
