# Generated by Django 5.1.7 on 2025-12-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_lecture_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
    ]
